### ISSUE TITLE
Support code folding in the blog

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-blog#13]
If we include an R code chunk and don't suppress the inclusion of the code, it appears as an inline code chunk right in the text.

R Markdown normally supports code folding, where the chunk initially appears hidden and a little "Code" button makes it appear. But Blogdown doesn't support that unless we manually add some JS to the theme. A couple links:

https://stackoverflow.com/questions/45360998/code-folding-in-bookdown
https://www.jepusto.com/code-folding-with-blogdown-academic/

Can we add something similar to the Hugo theme we're using, so we can include code chunks without disrupting the flow of the text?

**Comment by adamperer** [comment]
@sgratzl would it be possible for you to estimate how much work this would be?

**Comment by sgratzl** [comment]
around half an hour, see PR
