### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-blog#18]
We got access to the Delphi analytics account. We have tracking ID `UA-88748454-1`.

@sgratzl, can you integrate this into the template? Here's the current recommended code:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-88748454-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-88748454-1');
</script>
```

Looks like there's some built-in support in the template; not sure how it works.

**Comment by sgratzl** [comment]
as far as I know you just have to enter the id here:

https://github.com/cmu-delphi/delphi-blog/blob/main/config.toml#L5
