### ISSUE TITLE
Show full article content in RSS feed so we can share to R-bloggers

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-blog#27]
[R-bloggers](https://www.r-bloggers.com/) aggregates posts related to R to a wider audience; you can join by submitting your RSS feed for review, but they say:

> Submit a feed with full content, abstract/excerpts will not be accepted – this content will be shown in full in R-bloggers’ feed and email. Here are a few tips for how to get it done. On WordPress blogs you can fix this by going to settings -> reading -> “For each article in a feed, show” -> “Full text”. On Hugo blogs (blogdown blogs)  you can try the following:
Configure the default RSS template given here: https://gohugo.io/templates/rss/#the-embedded-rss-xml
replacing `{{ .Summary | html }}` with `{{ .Content | html }}`

Our [current feed](https://delphi.cmu.edu/blog/index.xml) only includes excerpts; can we edit the template as requested and test that the generated HTML looks good?

@sgratzl, would this be easy to do?

**Comment by ryantibs** [comment]
Thanks @capnrefsmmat @sgratzl. Sorry to be annoying again, but any updates here on #28 being ready-to-go? Since this would help our blog's reach, pretty much automatically, it would be nice to sort it out.

**Comment by sgratzl** [comment]
> Thanks @capnrefsmmat @sgratzl. Sorry to be annoying again, but any updates here on #28 being ready-to-go? Since this would help our blog's reach, pretty much automatically, it would be nice to sort it out.

from my side it is ready, just needs to be tested again from your side

**Comment by sgratzl** [comment]
current feed with the new version at https://delphi.cmu.edu/blog/index.xml includes the full text - closing
