### ISSUE TITLE
Figure out how to set teaser images for posts

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-blog#30]
It'd be great to have teaser images for posts. As Ryan suggests:

> What if for each post, in addition to the abstract, we had a little image associated with it, which was a nice plot that we chose from that post? That could grab somebody’s attention as well as an abstract.

We could put this image in the front page post listing, as well as embedding the necessary tags so social media sites know to use the image as the post preview image.

I'm not sure how to do this. We generate plenty of plots in each post, but they're SVGs, and a bit of Googling suggests that Open Graph doesn't like SVGs. I guess there are a few options:

1. Manually generate a PNG for the image, upload it, and then use a variable in the post header to point to the image. Have the Hugo templates use this variable for the image embed.
2. Somehow customize Blogdown so we can set a chunk option on a code chunk to tell it "make this into the teaser", and it automatically makes a PNG version and sets the appropriate header.

Image or not, we can also add [Open Graph tags](https://ogp.me/) including the post summary and site name, to make sharing better.

**Comment by sgratzl** [comment]
https://metatags.io/ is a nice site for testing meta data tags. 

I started with https://github.com/cmu-delphi/delphi-blog/pull/31 which uses the `manually generate and save a static image` approach. I think it it the easiest one and one can tune the image (such as size) to the desired output.

**Comment by ryantibs** [comment]
Thanks @capnrefsmmat @sgratzl.  Any updates here on #31?  Sam, why is it still marked as a draft, are you not satisfied with it?  

Can somebody build it and post a screenshot here?

**Comment by sgratzl** [comment]
> Thanks @capnrefsmmat @sgratzl. Any updates here on #31? Sam, why is it still marked as a draft, are you not satisfied with it?
> 
> Can somebody build it and post a screenshot here?

it is marked as draft since I'm not sure whether this is the approach you are looking for and I assume it will require some fine tuning to fit to your needs

**Comment by sgratzl** [comment]
closing since www-main version has teaser images
